ijug-ev/JavaLand

- Community-Aktivitäten/README.md
Erster Entwurf einer öffentlichen Seite für die CAs.
Diese wird demnächst entsprechend um den eigentlichen CfP erweitert.
> Erster Entwurf Community-Aktivitäten

- Community-Aktivitäten/README.md
Vorschlag für eine CfP-Seite für die CAs.
Bitte um kurzfristiges Voting, da der CfP für das Programm bereits morgen startet!
> Entwurf CA-CfP

- Community-Aktivitäten/README.md
Entwurf, wie wir den Planungsstand der CAs dokumentieren könnten. Gerne zukünftige Aktualisierungen des Planungsstandes dann auch ohne PR sondern per direkten push durch Dich oder mich.
> Die ersten vier in Planung befindlichen CAs 2021

- Community-Aktivitäten/README.md
Diesen CAs sage ich heute fest zu, da wir sie bereits im Prospekt angekündigt haben, über die anderen entscheiden wir nach Klärung der Raumsituation.
> Erster Batch feste Zusagen

- Community-Aktivitäten/README.md
@mkarg hier mein Vorschlag für den Eintrag.
> Meet-the-Lib

- Community-Aktivitäten/README.md
A little late, but I totally forgot to create this PR.
> Update karate workshop description

- Community-Aktivitäten/README.md
@TimRiemer Bennet hat mir gerade per PM zugesagt, das JavaLand Jogging *jedes Jahr* durchzuführen; wir dürfen ihn pauschal immer aufführen. Von meiner Seite ist das OK.
> JavaLand Jogging

- Community-Aktivitäten/README.md
> Community Unkonferenz

- Community-Aktivitäten/README.md
sorry ich hatte die Links vergessen hinzuzufügen..
> docToolchain jetzt mit Links

- Community-Aktivitäten/README.md
Es hat sich ein Wunschslot ergeben
> 22 doc toolchain Wunschslot

- Community-Aktivitäten/README.md
neue Community-Aktivität, falls sich ein Sponsor findet
> Hacking the 2040

- Community-Aktivitäten/README.md
Entschuldigt die recht späte Einreichung. Diesen Workshop haben Falk und ich bereits zweimal auf der JavaLand gegeben. Dieses Jahr haben wir den Workshop ein bisschen aufgefrischt.
> Funktionale Programmierung in Java Workshop

- Community-Aktivitäten/README.md
@mkarg hier wie gestern besprochen meine Last-Minute-Einreichungen.
Sorry, ist etwas später geworden.
Einen Verbessrungsvorschlag hätte ich auch noch: Können wir Tags für vergangene Veranstaltungen setzen? Ich war froh, dass ich noch eine veraltete Kopie des Repos hatte und dort spicken konnte... ;-)
> Meet-the-Lib und EF Projekt Workshop ergänzt

- Community-Aktivitäten/README.md
Der Commit beinhaltet einen Antrag für Kommunity Workshop von JUG Darmstadt, in dem wir ein ChatGPT-Klon in Kotlin von Grund auf bauen...
> Kotlin GPT Workshop

- Community-Aktivitäten/README.md
Siehe https://github.com/ijug-ev/JavaLand/pull/44, das hier ist der richtige Branch :)
> Added Dojos, Sebastian

- Community-Aktivitäten/README.md
Willst du mal drüber gucken, @JOpsDev, bevor ich das einreiche?
> Vorschlag für JavaLand UnKonf

- Community-Aktivitäten/README.md
Passend zum Veranstaltungsort sollten wir doch ein Rennen veranstalten, oder?
> JavaLand4Kidadults - Das große Rennen

- Community-Aktivitäten/README.md
> AI/KI instead of ChatGPT

- Community-Aktivitäten/README.md
Meet-the-Lib und wie werde ich Eclipse Contributor Community-Aktivitäten.
Passt gut in den Hackergarten.
> 2024 Jan Westerkamp

- Community-Aktivitäten/README.md
> FP Workshop

- Community-Aktivitäten/README.md
Wie bereits die Jahre zuvor wieder die beiden Dojos. Ich warte noch auf eine Rückmeldung, aber so habt ihr schon mal etwas im Posteingang.
> Coding Dojo & Architecture Dojo

- Community-Aktivitäten/README.md
Leider war die JavaLand4Kidults letztes Jahr nicht so erfolgreich. Hier meine Idee für dieses Jahr: Duke Maskottchen bauen und gleichzeitig etwas Gutes tun. Wie ist eure Meinung dazu?
Viele Grüße,
Fin
> JavaLand4Kidults - 1. Rohfassung

- Community-Aktivitäten/README.md
Bissel knapp, aber leider habe ich es nicht früher geschafft..
> Let's try OpenRewrite
